baseURL = 'https://blog.gudrian.org/'
languageCode = 'en'
title = 'Nørdlicht'
theme = 'gokarna'
enableRobotsTXT = true
enableEmoji = true

[params]
  showPostsOnHomePage = "recent"

  socialIcons = [
    {name = "mastodon", url = "https://social.tchncs.de/@cgudrian"},
    {name = "linkedin", url = "https://www.linkedin.com/in/christian-gudrian-80756a82"},
    {name = "email", url = "mailto:blog@gudrian.org"}
  ]

  showBackToTopButton = true
  togglePreviousAndNextButtons = "true"
  dateFormat = "January 2, 2006"

  customFooterHTML = '''
    <small><a href="/legal/">Legal Notice</a></small>
  '''

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1
  
  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7